/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.21
 * Generated at: 2015-12-07 17:50:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html ng-app=\"ui.bootstrap.demo\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>ScanBook</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"angular.min.js\"></script>\r\n");
      out.write("<script src=\"angular-animate.js\"></script>\r\n");
      out.write("<script src=\"ang.js\"></script>\r\n");
      out.write("<script src=\"GoogleSignIn.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"http://angular-ui.github.io/bootstrap/ui-bootstrap-tpls-0.14.3.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write("div.space {\r\n");
      out.write("\tpadding-top: 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".img-circle {\r\n");
      out.write("\tborder-radius: 100%;\r\n");
      out.write("\twidth: 10%;\r\n");
      out.write("\theight: 10%;\r\n");
      out.write("}\r\n");
      out.write("tr {\r\n");
      out.write("\twidth: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("\toverflow: scroll;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div ng-controller=\"AccordionCtrl\">\r\n");
      out.write("\t\t<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\t\tdata-target=\"#myNavbar\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t<a class=\"navbar-brand\" href=\"#\">ScanBook</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"collapse navbar-collapse\" id=\"myNavbar\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t\t\t<li style=\"text-align: center;\"><img align=\"right\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"imgHolder\" class=\"img-circle\"></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a id=\"uName\"> Guest </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><label id='loginId' hidden=\"true\"></label> <a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\tonclick='login();' id=\"loginText\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-log-in\"></span> Login</a> <a\r\n");
      out.write("\t\t\t\t\t\t\tStyle=\"display: none\" ID=\"logoutText\" target='myIFrame'\r\n");
      out.write("\t\t\t\t\t\t\tng-click=\"logout()\"\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"myIFrame.location='https://www.google.com/accounts/Logout'; startLogoutPolling();return false;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-log-out\"></span> Logout\r\n");
      out.write("\t\t\t\t\t\t</a> <iframe name='myIFrame' id=\"myIFrame\" style='display: none'></iframe></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t\t<uib-accordion ng-model=\"a\" close-others=\"true\"> <uib-accordion-group\r\n");
      out.write("\t\t\theading=\"Add Books\" panel-class=\"panel-success\">\r\n");
      out.write("\t\t<form name=\"addForm\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t\t\t<input class=\"form-control\" name=\"ncode\" id=\"code\" ng-model=\"scode\"\r\n");
      out.write("\t\t\t\t\t\ttype=\"number\" type=\"text\" placeholder=\"Book Code\"\r\n");
      out.write("\t\t\t\t\t\tng-required=\"true\">\r\n");
      out.write("\t\t\t\t\t<div class=\"space\"></div>\r\n");
      out.write("\t\t\t\t\t<input class=\"form-control\" id=\"title\" name=\"ntitle\"\r\n");
      out.write("\t\t\t\t\t\tng-model=\"stitle\" type=\"text\" placeholder=\"Book Title\"\r\n");
      out.write("\t\t\t\t\t\tng-required=\"true\">\r\n");
      out.write("\t\t\t\t\t<div class=\"space\"></div>\r\n");
      out.write("\t\t\t\t\t<input class=\"form-control\" id=\"author\" name=\"nauthor\"\r\n");
      out.write("\t\t\t\t\t\tng-model=\"sauthor\" type=\"text\" placeholder=\"Book Author\"\r\n");
      out.write("\t\t\t\t\t\tng-required=\"true\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-2\">\r\n");
      out.write("\t\t\t\t\t<div class=\"space\"></div>\r\n");
      out.write("\t\t\t\t\t<input class=\"form-control\" id=\"pages\" name=\"npages\"\r\n");
      out.write("\t\t\t\t\t\tng-model=\"spages\" placeholder=\"Total Pages\" type=\"number\"\r\n");
      out.write("\t\t\t\t\t\tng-required=\"true\">\r\n");
      out.write("\t\t\t\t\t<div class=\"checkbox\">\r\n");
      out.write("\t\t\t\t\t\t<label><input type=\"checkbox\" ng-model=\"sread\">Have\r\n");
      out.write("\t\t\t\t\t\t\tRead</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<uib-rating ng-model=\"rate\" max=\"max\" readonly=\"isReadonly\"\r\n");
      out.write("\t\t\t\t\t\ton-hover=\"hoveringOver(value)\" on-leave=\"overStar = null\"\r\n");
      out.write("\t\t\t\t\t\ttitles=\"['one','two','three']\" aria-labelledby=\"default-rating\"></uib-rating>\r\n");
      out.write("\t\t\t\t\t<div class=\"space\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t\t\t<div align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-sm btn-success\"\r\n");
      out.write("\t\t\t\t\t\t\tng-click=\"addForm.$valid && Save()\">Save</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"space\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"alert alert-warning\" ng-show=\"!addForm.$valid\">\r\n");
      out.write("\t\t\t\t\t\t<strong>Warning!</strong> Please enter all the details!!!.\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t</uib-accordion-group> <uib-accordion-group heading=\"View Books\" panel-class=\"panel-info\">\r\n");
      out.write("\t\t<form name=\"viewForm\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t\t\t<input type=\"number\" id=\"vsearch\" name=\"nsearch\" min=\"0\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"Please enter the barcode\" ng-model=\"dynamicFrom\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"form-control\" ng-required=\"true\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-2\" align=\"left\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-sm btn-info\" ng-model=\"vView\"\r\n");
      out.write("\t\t\t\t\t\tng-click=\"viewForm.$valid && viewBook()\">View</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<div id=\"vdetails\" ng-show=\"myValue\" class=\"ng-hide\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t\t<label id=\"vcode\" ng-model=\"vmcode\">Book Code : </label>{{vmcode}}\r\n");
      out.write("\t\t\t\t\t<div class=\"space\"></div>\r\n");
      out.write("\t\t\t\t\t<label id=\"vtitle\" ng-model=\"vmtitle\">Book Title : </label>{{vmtitle}}\r\n");
      out.write("\t\t\t\t\t<div class=\"space\"></div>\r\n");
      out.write("\t\t\t\t\t<label id=\"vauthor\" ng-model=\"vmauthor\">Book Author : </label>{{vmauthor}}\r\n");
      out.write("\t\t\t\t\t<div class=\"space\"></div>\r\n");
      out.write("\t\t\t\t\t<label id=\"vpages\" ng-model=\"vmpages\">Total Pages : </label>{{vmpages}}\r\n");
      out.write("\t\t\t\t\t<div class=\"space\"></div>\r\n");
      out.write("\t\t\t\t\t<span><input disabled=\"disabled\" type=\"checkbox\" id=\"vread\"\r\n");
      out.write("\t\t\t\t\t\tng-model=\"vmread\" value=\"\">Have Read</span>\r\n");
      out.write("\t\t\t\t\t<div class=\"space\"></div>\r\n");
      out.write("\t\t\t\t\t<uib-rating ng-model=\"vrate\" max=\"max\"\r\n");
      out.write("\t\t\t\t\t\ttitles=\"['one','two','three']\" aria-labelledby=\"default-rating\"></uib-rating>\r\n");
      out.write("\t\t\t\t\t<span class=\"label\"\r\n");
      out.write("\t\t\t\t\t\tng-class=\"{'label-danger': vpercent<30,'label-warning': vpercent>=30 && vpercent<60, 'label-info': vpercent>=60 && vpercent<80, 'label-success': vpercent>=80}\">{{vpercent}}%</span>\r\n");
      out.write("\t\t\t\t\t<div class=\"space\"></div>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-sm btn-danger\"\r\n");
      out.write("\t\t\t\t\t\tng-click=\"Clear()\">Clear Search</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</uib-accordion-group> <uib-accordion-group heading=\"Delete Books\"\r\n");
      out.write("\t\t\tpanel-class=\"panel-danger\">\r\n");
      out.write("\t\t<form name=\"delForm\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t\t\t<input type=\"number\" id=\"vdel\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"Please enter the barcode\" ng-model=\"dynamicdelete\"\r\n");
      out.write("\t\t\t\t\t\tmin=\"0\" name=\"ndelete\" ng-required=\"true\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-4\" align=\"left\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-sm btn-danger\"\r\n");
      out.write("\t\t\t\t\t\tng-model=\"vdelBtn\" ng-click=\"delForm.$valid && deleteBook()\">Delete</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t</uib-accordion-group> <uib-accordion-group heading=\"My Books\" panel-class=\"panel-warning\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-4\" align=\"left\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-sm btn-warning\"\r\n");
      out.write("\t\t\t\t\tng-model=\"vgetBtn\" ng-click=\"getBook()\">{{getLoad}}</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"space\"></div>\r\n");
      out.write("\t\t<div style=\"height:100px;overflow:auto;\">\r\n");
      out.write("\t\t\t<table id=\"myTable\" class=\"table table-condensed\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</uib-accordion-group> </uib-accordion>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
